### ISSUE TITLE
Seems Broken

### ISSUE THREAD

**Issue by olls** [itsapi/news_feed#1]
No news items load... Or it only loads items if one source is selected

**Comment by geraintwhite** [comment]
Details? (browser, OS, circumstances, errors in console, etc...)

**Comment by olls** [comment]
ChromeOS, no errors, it makes the requests and gets a response. It seems to only load items if one source is selected.

**Comment by geraintwhite** [comment]
Hmm, I can reproduce on Chrome Mac OS. Google must have changed something in their API - it worked when I checked fairly recently.

**Comment by olls** [comment]
The fact it works with just one (any) source seems to suggest it's our code...

**Comment by geraintwhite** [comment]
Error 400 "missing query parameter 'q'" when trying to load guardian.co.uk feed

**Comment by geraintwhite** [comment]
Works with bbc.co.uk and telegraph.co.uk. Indicates it's a problem with guardian.co.uk feed. However we should handle the error.

**Comment by olls** [comment]
I'm not getting the error, but it seems to be making requests with blank URLs

**Comment by geraintwhite** [comment]
I was logging result at line 101

**Comment by olls** [comment]
[This](https://github.com/itsapi/news_feed/blob/master/main.js#L95) line:

`var feedURL = result.entries[0].url;`

is breaking it, the URL is blank in some results.

```
k.(anonymous function).A {h: function, status: Object, entries: Array[10], query: "site:http://cnn.com ", I: function…}
entries: Array[10]
0: Object
contentSnippet: "Find the latest breaking news and information on the top stories, weather, <br>↵business, entertainment, politics, and more. For in-depth coverage, CNN <br>↵provides&nbsp;..."
link: "http://www.cnn.com/"
title: "CNN.com: Breaking News, US, World, Weather, Entertainment <b>...</b>"
url: ""
```

**Comment by olls** [comment]
Nope, [this](https://github.com/itsapi/news_feed/blob/master/main.js#L127) line is the problem. We are checking to see if all of the feeds are loaded before displaying them, so if a feed fails, none ever load. We need to do this properly...

**Comment by geraintwhite** [comment]
We should put:

```
count++;
putInHTML(count, feeds, allFeeds);
```

in a callback and call it for every error and success.

**Comment by olls** [comment]
I was thinking more of getting rid of the count var, and doing it properly... But it's an old site, this will do

**Comment by geraintwhite** [comment]
What do you mean do it properly? How would you trigger an event after n
async processes have completed?

**Comment by olls** [comment]
Not reloading all the HTML several times per feed, even if it can't load it...

**Comment by olls** [comment]
Maybe something like this would be a cleaner way of implementing this: http://stackoverflow.com/a/11278104/1841416

**Comment by olls** [comment]
> Not reloading all the HTML several times per feed, even if it can't load it...

Oh, ignore that.
